# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liked_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
