# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liked_books', '0002_auto_20170922_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
